# Generated by Django 4.0 on 2024-03-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tel',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
