# Generated by Django 4.0 on 2024-03-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_myuser_delete_organisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='account_type',
        ),
    ]
