# Generated by Django 4.0 on 2024-03-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_myuser_organisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisateur',
            name='account_type',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
