# Generated by Django 4.0 on 2024-03-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_organisateur_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisateur',
            name='account_type',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='organisateur',
            name='tel',
            field=models.TextField(blank=True, default=None),
        ),
    ]
