# Generated by Django 4.0 on 2024-03-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointdevente',
            name='lieu',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
