# Generated by Django 4.0 on 2024-03-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_pointdevente_lieu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sub',
            field=models.CharField(blank=True, default='', max_length=50, null=True, unique=True),
        ),
    ]
