# Generated by Django 4.0 on 2024-03-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_organisateur_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisateur',
            name='account_type',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organisateur',
            name='tel',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
