# Generated by Django 4.0 on 2024-03-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_customuser_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sub',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
