# Generated by Django 4.0 on 2024-03-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_organisateur_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisateur',
            name='tel',
            field=models.TextField(default=None),
        ),
    ]
