# Generated by Django 4.0 on 2024-03-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_organisateur_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisateur',
            name='tel',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
