# Generated by Django 4.0 on 2024-03-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0009_alter_organisateur_tel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organisateur',
            new_name='MyUser',
        ),
    ]
