# Generated by Django 4.0 on 2024-03-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_customuser_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sub',
            field=models.CharField(default=None, max_length=50, null=True, unique=True),
        ),
    ]
