# Generated by Django 4.0 on 2024-03-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_organisateur_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='tel',
            field=models.TextField(default=None, null=True),
        ),
    ]
