# Generated by Django 4.0 on 2024-03-16 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_customuser_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointdevente',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pointdevente_related', to='account.customuser'),
        ),
    ]
