# Generated by Django 4.0 on 2024-03-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0016_alter_myuser_account_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'GlobalUser'},
        ),
        migrations.AlterField(
            model_name='pointdevente',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='pointdevente_groups', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='pointdevente',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='pointdevente_user_permissions', to='auth.Permission'),
        ),
        migrations.AlterField(
            model_name='pointdevente',
            name='username',
            field=models.TextField(),
        ),
    ]
