# Generated by Django 4.0 on 2024-03-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_rename_lieu_pointdevente_lieu_pdv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointdevente',
            old_name='lieu_pdv',
            new_name='lieu',
        ),
        migrations.RenameField(
            model_name='pointdevente',
            old_name='tel_pdv',
            new_name='tel',
        ),
        migrations.RemoveField(
            model_name='pointdevente',
            name='username_pdv',
        ),
        migrations.AlterField(
            model_name='pointdevente',
            name='password',
            field=models.CharField(default=None, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pointdevente',
            name='username',
            field=models.TextField(unique=True),
        ),
    ]
