# Generated by Django 4.0 on 2024-02-26 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(max_length=255, unique=True)),
                ('lieu', models.TextField(default=None, max_length=25)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
