# Generated by Django 4.0 on 2024-03-15 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(max_length=255, unique=True)),
                ('lieu', models.TextField(default=None, max_length=25)),
                ('image', models.ImageField(upload_to='event/')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evenement_related', to='account.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ticket', models.TextField(max_length=24)),
                ('nb_ticket', models.IntegerField()),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_related', to='eventManagement.evenement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='sponsors/')),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='related_sponsors', to='eventManagement.evenement')),
            ],
        ),
        migrations.CreateModel(
            name='PointDeVenteToEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PDVToEvent_related', to='eventManagement.evenement')),
                ('pdv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.pointdevente')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ticket', models.TextField(max_length=24)),
                ('nb_ticket', models.IntegerField()),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_related', to='eventManagement.evenement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ticket', models.TextField(max_length=24)),
                ('nb_ticket', models.IntegerField()),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_related', to='eventManagement.evenement')),
                ('pointdevente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='account.pointdevente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
