# Generated by Django 4.0 on 2024-02-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('eventManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evenements',
            new_name='Evenement',
        ),
    ]
