# Generated by Django 4.0 on 2024-03-16 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_pointdevente_owner'),
        ('eventManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addticket',
            name='nb_ticket',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='addticket',
            name='pointdevente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='account.pointdevente'),
        ),
        migrations.AlterField(
            model_name='archiveticket',
            name='nb_ticket',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='nb_ticket',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
