# Generated by Django 5.0.3 on 2024-03-27 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventManagement', '0002_ticketqrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketqrcode',
            name='ID_ticket',
        ),
    ]
