# Generated by Django 4.0 on 2024-02-26 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventManagement', '0002_rename_evenements_evenement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='evenement',
            name='sponsors',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sponsors', to='eventManagement.imagesponsors'),
        ),
    ]
