# Generated by Django 4.0 on 2024-02-26 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventManagement', '0003_imagesponsors_evenement_sponsors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageSponsors',
            new_name='ImageSponsor',
        ),
    ]
