# Generated by Django 5.0.3 on 2024-03-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventManagement', '0003_remove_ticketqrcode_id_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketqrcode',
            name='type_ticket',
            field=models.TextField(default=None, max_length=24),
            preserve_default=False,
        ),
    ]
