# Generated by Django 4.0 on 2024-02-26 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventManagement', '0004_rename_imagesponsors_imagesponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='sponsors',
        ),
        migrations.DeleteModel(
            name='ImageSponsor',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='related_sponsors', to='eventManagement.evenement'),
        ),
    ]
