# Generated by Django 4.0 on 2024-07-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventManagement', '0005_evenement_type_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='H_debut',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='H_fin',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
    ]
