# Generated by Django 4.0 on 2024-02-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventManagement', '0006_ticket_archiveticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='image',
        ),
        migrations.AddField(
            model_name='evenement',
            name='sponsors_images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='image_url',
            field=models.TextField(default=None),
        ),
    ]
