# Generated by Django 4.0 on 2024-07-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventManagement', '0006_evenement_h_debut_evenement_h_fin_evenement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='addticket',
            name='prix',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='archiveticket',
            name='prix',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='prix',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
