# Generated by Django 4.0 on 2024-07-25 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_account_type_alter_customuser_tel'),
        ('eventManagement', '0007_addticket_prix_archiveticket_prix_ticket_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointdeventetoevenement',
            name='pdv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PDVToEvent_related', to='account.pointdevente'),
        ),
    ]
