# Generated by Django 4.0 on 2024-02-29 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventManagement', '0008_remove_evenement_sponsors_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='slug',
            field=models.SlugField(default=None),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='related_sponsors', to='eventManagement.evenement'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='image',
            field=models.ImageField(default=None, upload_to='sponsors/'),
        ),
    ]
