# Generated by Django 4.0 on 2024-03-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventManagement', '0009_alter_evenement_slug_alter_sponsor_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='image',
            field=models.ImageField(upload_to='event/'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
